# Generated by Django 5.1.3 on 2025-03-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['-usage_count', 'name']},
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='category',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='last_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
